# Generated by Django 4.1.3 on 2022-11-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_receta_new_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='new_field',
            field=models.FileField(default='settings.MEDIA_ROOT/fotos/croquetas-de-jamon-super-jugosas.jpeg', upload_to='media/fotos'),
        ),
    ]
