# Generated by Django 4.1.3 on 2022-11-07 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0003_alter_receta_new_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='new_field',
            new_name='foto2',
        ),
    ]
