# Generated by Django 4.1.3 on 2022-11-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0004_rename_new_field_receta_foto2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='foto2',
            field=models.FileField(default='settings.MEDIA_ROOT/fotos/blanco.jpeg', upload_to='media/fotos'),
        ),
    ]
