# Generated by Django 4.1.3 on 2022-11-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0007_alter_receta_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='foto',
            field=models.FileField(upload_to='media/fotos'),
        ),
    ]
